### ISSUE TITLE
Great Game

### ISSUE THREAD

**Issue by suresh-shinde-engineer** [kevinroast/arena5#1]
Hello Kevin,
I am beginner in Canvas Javascript Games, I am curious to learn, I know basics of HTML5, CSS3, Javascript.
Where i to start...Please tell me best tutorials to learn.

I am doing customization in your code, like I want to write text on enemy objects or can i replace objects to other images?

**Comment by kevinroast** [comment]
I would suggest searching on the web for html5 and javascript tutorials on the subject. There are several good books also. If you want to code games, I highly suggest a book on game mathematics e.g. https://www.amazon.co.uk/gp/product/0123742978

**Comment by suresh-shinde-engineer** [comment]
Thank you very mutch.
